PaymentMethod.create(name: 'Pix')
PaymentMethod.create(name: 'Cartão de crédito')
PaymentMethod.create(name: 'Cartão de débito')
PaymentMethod.create(name: 'Boleto bancário')
PaymentMethod.create(name: 'Transação bancária')